{
  "language": "php",
  "php": "7.0.21"
  "sudo": false,
  "cache": {
    "directories": [
      "$HOME/.composer/cache",
      "node_modules",
    ]
  },
  "services": [
    "mysql",
    "memcached",
    "redis-server"
  ],
  "before_install": [
    "php -i | grep xdebug",
    "npm install && npm run dev",
    "mysql -e 'CREATE DATABASE IF NOT EXISTS webshelf;'",
    "echo \"extension = memcached.so\" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini",
    "printf \"\\n\" | pecl install -f redis",
    "travis_retry composer self-update",
    "composer install --dev",
    "php artisan migrate --force",
  ],
  "install": [
    "if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi",
    "if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi",
    "if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi"
  ],
  "script": "vendor/bin/phpunit --coverage-clover build/logs/clover.xml",
  "after_script": "php vendor/bin/codacycoverage clover",
  "global_env": "setup=basic",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
