{
  "language": "php",
  "php": "7.0.21",
  "sudo": false,
  "cache": {
    "directories": [
      "$HOME/.composer/cache"
    ]
  },
  "services": [
    "mysql",
    "memcached",
    "redis-server"
  ],
  "before_install": [
    "mysql -e 'CREATE DATABASE IF NOT EXISTS webshelf;'",
    "if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi",
    "echo \"extension = memcached.so\" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini",
    "printf \"\\n\" | pecl install -f redis",
    "travis_retry composer self-update",
    "composer install --dev",
    "php artisan migrate --force",

  ],
  "install": [
    "if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi",
    "if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi",
    "if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi"
  ],

  "notifications": "slack: webshelf:ZLh2j0rMeHbQ68YgoqhLKnT5",
  "script": "vendor/bin/phpunit",
  "after_script": "php vendor/bin/codacycoverage",
  "global_env": "setup=basic",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
